"""
app/exceptions.py - Custom app exceptions go here
"""

class ValidationError(ValueError):
    pass
